# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-20 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Headline',
            new_name='political',
        ),
    ]
