# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-21 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_entertainment_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='political',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
