# Generated by Django 3.0.4 on 2020-03-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_political_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=200)),
                ('image_src', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('link', models.TextField()),
                ('text', models.TextField()),
                ('date', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='entertainment',
        ),
        migrations.DeleteModel(
            name='political',
        ),
        migrations.DeleteModel(
            name='sport',
        ),
    ]
