# Generated by Django 3.0.4 on 2020-03-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200325_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
