# Generated by Django 3.0.4 on 2020-03-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_article_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
